### ISSUE TITLE
Use new URL format with query parameter instead of hash for line numbers

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph-vscode-DEPRECATED#182]
The extension should be updated to use the new `?L1:3` URL format instead of the old `#L1:3` format. See https://github.com/sourcegraph/sourcegraph/pull/22058

**Comment by felixfbecker** [comment]
I think the extension should generate the same parameters until we know all customers have upgraded to 3.29 (which is the first version that supports `?` parameters). Until then we should just implement redirects in the web app so that the URL gets changed to the new pattern automatically immediately when the page loads.

**Comment by limitedmage** [comment]
Actually, the URL params are not generated by the extensions but rather the Go code, see  https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/editor.go?L170:37 
So we might need to move the issue there :)

**Comment by limitedmage** [comment]
Moved to https://github.com/sourcegraph/sourcegraph/issues/22858
